### ISSUE TITLE
The file “get_img_crop.py” is missing.

### ISSUE THREAD

**Issue by pinkbluer** [Maggiking/SRGAN-PyTorch#1]
Hi, Maggiking! Thanks for your code.

1. The file “get_img_crop.py” is missing. 

2. SRGAN seems only have a little improvement, compared to Bicubic.

**Comment by ziwei-jiang** [comment]
Hi,
Thanks for the comments! I forgot to push the latest version of the code and lost access to the computer I worked on. But I found a backup copy of the code on my laptop with "get_img_crop.py. This should work now.
For the image quality, I think because I didn't train the model enough time. I stopped training after the PSNR is higher than the bicubic.
I'll try to train the model further and see if it would improve the result.

**Comment by pinkbluer** [comment]
> Hi,
> Thanks for the comments! I forgot to push the latest version of the code and lost access to the computer I worked on. But I found a backup copy of the code on my laptop with "get_img_crop.py. This should work now.
> For the image quality, I think because I didn't train the model enough time. I stopped training after the PSNR is higher than the bicubic.
> I'll try to train the model further and see if it would improve the result.

Thanks for your response, I really appreciate it.
